version: '2'
services:
  es:
    image: clselasticsearch:0.1
    volumes:
    - /var/cls_logs_storage/esdata:/usr/share/elasticsearch/data
  redis:
    image: redis
    ports:
    - "7009:6379"
  IndexerLogstash:
    image: clsindexer:0.1
    entrypoint: logstash -f /config-dir/logstash.conf
  #ShipperLogstash:
    #image: clsagent:0.1
    #volumes:
    #- /path/to/log/dir:/logs
    #entrypoint: logstash -f /config-dir/shipper.conf
  Kibana:
    image: kibana
    ports:
    - "7008:5601"
    environment:
    - ELASTICSEARCH_URL=http://es:9200/
